AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2

Parameters:
  SystemName:
    Description: System name.
    Type: String
  EnvName:
    Description: Environmental name.
    Type: String
    AllowedValues: [dev, stg, prod]

Resources:
# ------------------------------------------------------- #
# EIP
# ------------------------------------------------------- #
  EIPCloudNine:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: i-06dec5b68a497d6cc
# ------------------------------------------------------- #
# SGIngress
# ------------------------------------------------------- #
  SGIngressEIP:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: { "Fn::ImportValue": !Sub "${SystemName}${EnvName}-sg-ingress-id" }
      IpProtocol: tcp
      FromPort: 10080
      ToPort: 10080
      CidrIp: !Join [ '', [!Ref EIPCloudNine, '/32']]
      Description: HTTP internal for Cloud9
